<?php
// /app/php_app/install/index.php - Web installer

$lockFile = __DIR__ . '/../config/install.lock';
$configFile = __DIR__ . '/../config/config.php';
$schemaFile = __DIR__ . '/schema.sql';

if (file_exists($lockFile) && !isset($_GET['force'])) {
    http_response_code(403);
    die('<h1>Instalação já concluída</h1><p>Remova <code>config/install.lock</code> para reinstalar. Ou adicione <code>?force=1</code> ao URL.</p>');
}

require_once __DIR__ . '/../vendor/autoload.php';

$step = (int)($_GET['step'] ?? 1);
$error = null;
$config = [];

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $config = $_POST;
    try {
        if ($step === 2) {
            // Test DB connection
            $dsn = "mysql:host={$config['db_host']};port={$config['db_port']};charset=utf8mb4";
            $pdo = new PDO($dsn, $config['db_user'], $config['db_pass'], [PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION]);
            // Try select database
            $pdo->exec("CREATE DATABASE IF NOT EXISTS `{$config['db_name']}` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci");
            $pdo->exec("USE `{$config['db_name']}`");
            $step = 3;
        } elseif ($step === 3) {
            // Create schema + admin + write config
            $dsn = "mysql:host={$config['db_host']};port={$config['db_port']};dbname={$config['db_name']};charset=utf8mb4";
            $pdo = new PDO($dsn, $config['db_user'], $config['db_pass'], [PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION]);
            $sql = file_get_contents($schemaFile);
            $pdo->exec($sql);

            // Admin account
            if (strlen($config['admin_password']) < 6) throw new Exception('Password mínima de 6 caracteres');
            $uid = strtolower(bin2hex(random_bytes(16)));
            // UUID v4 format
            $d = random_bytes(16); $d[6] = chr(ord($d[6]) & 0x0f | 0x40); $d[8] = chr(ord($d[8]) & 0x3f | 0x80);
            $uid = vsprintf('%s%s-%s-%s-%s-%s%s%s', str_split(bin2hex($d), 4));
            $hash = password_hash($config['admin_password'], PASSWORD_BCRYPT);
            $perms = json_encode([
                'clients' => ['view','create','update','delete','import','export'],
                'products' => ['view','create','update','delete','import','export'],
                'suppliers' => ['view','create','update','delete'],
                'orders' => ['view','create','update','delete','pdf'],
                'users' => ['view','create','update','delete'],
                'logs' => ['view'],
                'settings' => ['view','update'],
            ]);
            $stmt = $pdo->prepare('INSERT INTO users (id,email,name,password_hash,role,permissions,active,created_at) VALUES (?,?,?,?,?,?,1,?)');
            $stmt->execute([$uid, strtolower(trim($config['admin_email'])), trim($config['admin_name']), $hash, 'admin', $perms, gmdate('Y-m-d H:i:s')]);

            // Settings
            $stmt = $pdo->prepare('INSERT INTO settings (id, company_name) VALUES ("global", ?)');
            $stmt->execute([$config['company_name'] ?: 'Order Management System']);

            // Import sample data if requested
            if (!empty($config['load_sample'])) {
                // Use seed script
                $seedFile = __DIR__ . '/seed_sample.php';
                if (file_exists($seedFile)) {
                    $SEED_PDO = $pdo; include $seedFile;
                }
            }

            // Write config.php
            $jwt = bin2hex(random_bytes(32));
            $cfg = <<<PHP
<?php
// Auto-generated by installer. DO NOT commit this file.
return [
    'db_host' => {$q($config['db_host'])},
    'db_port' => (int){$q($config['db_port'])},
    'db_name' => {$q($config['db_name'])},
    'db_user' => {$q($config['db_user'])},
    'db_pass' => {$q($config['db_pass'])},
    'jwt_secret' => {$q($jwt)},
    'cors_origins' => {$q($config['cors_origins'] ?? '*')},
];
PHP;
            // Use var_export for escaping
            $cfgArr = [
                'db_host' => $config['db_host'],
                'db_port' => (int)$config['db_port'],
                'db_name' => $config['db_name'],
                'db_user' => $config['db_user'],
                'db_pass' => $config['db_pass'],
                'jwt_secret' => $jwt,
                'cors_origins' => $config['cors_origins'] ?? '*',
            ];
            file_put_contents($configFile, "<?php\nreturn " . var_export($cfgArr, true) . ";\n");
            file_put_contents($lockFile, gmdate('Y-m-d H:i:s'));
            $step = 4;
        }
    } catch (Throwable $e) {
        $error = $e->getMessage();
    }
}

function q($v) { return var_export((string)$v, true); }

?>
<!doctype html>
<html lang="pt">
<head>
<meta charset="utf-8">
<title>Instalação — ProdStock V1.1 Beta</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
* { box-sizing: border-box; }
body { font-family: -apple-system, Segoe UI, sans-serif; background: #f5f7fb; margin: 0; padding: 24px; color: #111827; }
.container { max-width: 620px; margin: 40px auto; background: white; border-radius: 12px; padding: 40px; box-shadow: 0 1px 3px rgba(0,0,0,0.08); }
h1 { margin: 0 0 6px; font-size: 26px; letter-spacing: -0.02em; }
.subtitle { color: #6b7280; margin: 0 0 28px; font-size: 14px; }
.steps { display: flex; gap: 8px; margin-bottom: 32px; }
.step { flex: 1; height: 4px; background: #e5e7eb; border-radius: 2px; }
.step.active { background: #0052ff; }
label { display: block; font-size: 12px; font-weight: 600; text-transform: uppercase; letter-spacing: 0.05em; margin-bottom: 6px; color: #374151; }
input[type=text], input[type=email], input[type=password], input[type=number] { width: 100%; padding: 10px 12px; border: 1px solid #e5e7eb; border-radius: 6px; font-size: 14px; margin-bottom: 16px; }
input:focus { outline: none; border-color: #0052ff; box-shadow: 0 0 0 3px rgba(0, 82, 255, 0.15); }
.row { display: grid; grid-template-columns: 1fr 1fr; gap: 12px; }
button { background: #0052ff; color: white; border: none; padding: 12px 20px; border-radius: 6px; font-size: 14px; font-weight: 600; cursor: pointer; width: 100%; }
button:hover { background: #0040cc; }
.error { background: #fef2f2; color: #991b1b; padding: 12px; border-radius: 6px; margin-bottom: 20px; font-size: 13px; }
.ok { background: #f0fdf4; color: #166534; padding: 16px; border-radius: 6px; margin: 20px 0; }
.muted { color: #6b7280; font-size: 12px; }
.hint { color: #6b7280; font-size: 12px; margin-top: -12px; margin-bottom: 16px; }
.checkbox { display: flex; align-items: center; gap: 8px; margin-bottom: 16px; }
.checkbox input { width: auto; margin: 0; }
a.btn-link { display: inline-block; background: #0052ff; color: white; padding: 10px 18px; border-radius: 6px; text-decoration: none; font-weight: 600; }
</style>
</head>
<body>
<div class="container">
    <h1>ProdStock V1.1 Beta</h1>
    <p class="subtitle">Instalador — Passo <?= $step ?> de 4</p>
    <div class="steps">
        <?php for ($i = 1; $i <= 4; $i++): ?>
            <div class="step <?= $i <= $step ? 'active' : '' ?>"></div>
        <?php endfor; ?>
    </div>

    <?php if ($error): ?>
        <div class="error"><strong>Erro:</strong> <?= htmlspecialchars($error) ?></div>
    <?php endif; ?>

    <?php if ($step === 1): ?>
        <h2>Requisitos</h2>
        <?php
        $req = [
            'PHP ≥ 8.0' => version_compare(PHP_VERSION, '8.0', '>='),
            'Extensão PDO MySQL' => extension_loaded('pdo_mysql'),
            'Extensão mbstring' => extension_loaded('mbstring'),
            'Extensão zip' => extension_loaded('zip'),
            'Extensão gd' => extension_loaded('gd'),
            'Pasta config/ gravável' => is_writable(__DIR__ . '/../config'),
        ];
        $allOk = !in_array(false, $req, true);
        ?>
        <ul style="line-height: 2; list-style: none; padding: 0;">
            <?php foreach ($req as $label => $ok): ?>
                <li><?= $ok ? '✅' : '❌' ?> <?= $label ?></li>
            <?php endforeach; ?>
        </ul>
        <?php if ($allOk): ?>
            <form method="get"><input type="hidden" name="step" value="2"><button type="submit">Continuar →</button></form>
        <?php else: ?>
            <div class="error">Corrija os requisitos em falta antes de continuar. Para a pasta config/, no cPanel use o File Manager → "Permissions" → 755.</div>
        <?php endif; ?>

    <?php elseif ($step === 2): ?>
        <h2>Base de Dados</h2>
        <p class="muted">Credenciais MySQL. No cPanel estão em "MySQL Databases".</p>
        <form method="post" action="?step=2">
            <label>Host</label>
            <input type="text" name="db_host" value="<?= htmlspecialchars($config['db_host'] ?? 'localhost') ?>" required>
            <label>Porto</label>
            <input type="number" name="db_port" value="<?= htmlspecialchars($config['db_port'] ?? '3306') ?>" required>
            <label>Nome da BD</label>
            <input type="text" name="db_name" value="<?= htmlspecialchars($config['db_name'] ?? '') ?>" required placeholder="cpaneluser_oms">
            <label>Utilizador</label>
            <input type="text" name="db_user" value="<?= htmlspecialchars($config['db_user'] ?? '') ?>" required>
            <label>Password</label>
            <input type="password" name="db_pass" value="<?= htmlspecialchars($config['db_pass'] ?? '') ?>">
            <button type="submit">Testar ligação e continuar →</button>
        </form>

    <?php elseif ($step === 3): ?>
        <h2>Utilizador Administrador + Empresa</h2>
        <form method="post" action="?step=3">
            <?php foreach (['db_host','db_port','db_name','db_user','db_pass'] as $k): ?>
                <input type="hidden" name="<?= $k ?>" value="<?= htmlspecialchars($_POST[$k] ?? $config[$k] ?? '') ?>">
            <?php endforeach; ?>
            <label>Nome da Empresa</label>
            <input type="text" name="company_name" value="<?= htmlspecialchars($config['company_name'] ?? 'A minha empresa') ?>" required>
            <hr style="margin: 24px 0; border: 0; border-top: 1px solid #e5e7eb;">
            <label>Nome do Administrador</label>
            <input type="text" name="admin_name" value="<?= htmlspecialchars($config['admin_name'] ?? 'Administrador') ?>" required>
            <label>Email do Administrador</label>
            <input type="email" name="admin_email" value="<?= htmlspecialchars($config['admin_email'] ?? '') ?>" required placeholder="admin@empresa.com">
            <label>Password (mín. 6 caracteres)</label>
            <input type="password" name="admin_password" required minlength="6">
            <label>CORS Origins (URLs permitidos, separados por vírgula)</label>
            <input type="text" name="cors_origins" value="<?= htmlspecialchars($config['cors_origins'] ?? '*') ?>" required placeholder="https://seudominio.com">
            <p class="hint">Use * para permitir todos (desenvolvimento). Em produção, indique o domínio exacto.</p>
            <div class="checkbox">
                <input type="checkbox" name="load_sample" id="sample" value="1" checked>
                <label for="sample" style="margin: 0; text-transform: none; font-weight: normal; letter-spacing: normal;">Carregar dados de exemplo (clientes e produtos em português)</label>
            </div>
            <button type="submit">Instalar agora ✓</button>
        </form>

    <?php elseif ($step === 4): ?>
        <div class="ok">
            <h2 style="margin: 0 0 8px;">✓ Instalação concluída</h2>
            <p style="margin: 0;">O sistema está pronto a usar. As credenciais de administrador foram guardadas.</p>
        </div>
        <p><strong>Próximos passos importantes:</strong></p>
        <ul>
            <li>Apague a pasta <code>install/</code> do servidor (ou renomeie-a) por segurança</li>
            <li>Verifique que o ficheiro <code>config/config.php</code> não é acessível publicamente</li>
            <li>Faça login e altere a password imediatamente</li>
        </ul>
        <p><a href="../index.html" class="btn-link">Ir para a aplicação →</a></p>
    <?php endif; ?>
</div>
</body>
</html>
